# DSC550_WK05.2_Kim-Schreck

In [2]:
# imports

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import nltk
import re
import string
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
import seaborn as sns
%matplotlib inline
import warnings
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

[nltk_data] Downloading package stopwords to /Users/gimjun-
[nltk_data]     won/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
# ignore warnings

warnings.filterwarnings('ignore')

In [4]:
# 5.2.01 
# convert tsv 01 to csv

with open('labeledTrainData.tsv', 'r') as tsvfile:
    reader = csv.reader(tsvfile, delimiter='\t')
    with open('labeledTrainData.csv', 'w') as csvfile:
        writer = csv.writer(csvfile)
        for row in reader:
            writer.writerow(row)

In [5]:
# 5.2.01 
# convert tsv 02 to csv

with open('testData.tsv', 'r') as tsvfile:
    reader = csv.reader(tsvfile, delimiter='\t')
    with open('testData.csv', 'w') as csvfile:
        writer = csv.writer(csvfile)
        for row in reader:
            writer.writerow(row)

In [6]:
# 5.2.01
# read dt01

dt01 = pd.read_csv('labeledTrainData.csv')
print(dt01.head())

       id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...


In [7]:
# 5.2.01
# read dt02

dt02 = pd.read_csv('testData.csv')
print(dt02.head())

         id                                             review
0  12311_10  Naturally in a film who's main themes are of m...
1    8348_2  This movie is a disaster within a disaster fil...
2    5828_4  All in all, this is a movie for kids. We saw i...
3    7186_2  Afraid of the Dark left me with the impression...
4   12128_7  A very accurate depiction of small time mob li...


In [8]:
# 5.2.01
# show columns

for col in dt01.columns:
    print(col)

id
sentiment
review


In [9]:
# 5.2.01
# show columns

for col in dt02.columns:
    print(col)

id
review


In [10]:
# 5.2.01
# assign variables

dt01_trn = dt01
dt02_tst = dt02

In [11]:
# 5.2.02
# split training and testing data

trn_x1 = dt01_trn['review']
trn_y1 = dt01_trn['review']
tst_x1 = dt02_tst['review']
tst_y1 = dt02_tst['review']
trn_x2=[]
tst_x2=[]

In [12]:
# 5.2.02
# return training data

print("training data")
print(trn_x1)

training data
0        With all this stuff going down at the moment w...
1        \The Classic War of the Worlds\" by Timothy Hi...
2        The film starts with a manager (Nicholas Bell)...
3        It must be assumed that those who praised this...
4        Superbly trashy and wondrously unpretentious 8...
                               ...                        
24995    It seems like more consideration has gone into...
24996    I don't believe they made this film. Completel...
24997    Guy is a loser. Can't get girls, needs to buil...
24998    This 30 minute documentary Buñuel made in the ...
24999    I saw this movie as a child and it broke my he...
Name: review, Length: 25000, dtype: object


In [13]:
# 5.2.02
# return testing data

print("testing data")
print(tst_x1)

testing data
0        Naturally in a film who's main themes are of m...
1        This movie is a disaster within a disaster fil...
2        All in all, this is a movie for kids. We saw i...
3        Afraid of the Dark left me with the impression...
4        A very accurate depiction of small time mob li...
                               ...                        
24995    Sony Pictures Classics, I'm looking at you! So...
24996    I always felt that Ms. Merkerson had never got...
24997    I was so disappointed in this movie. I am very...
24998    From the opening sequence, filled with black a...
24999    This is a great horror film for people who don...
Name: review, Length: 25000, dtype: object


In [14]:
# 5.2.03
# return count

cnt = CountVectorizer()
cnt_wrd=cnt.fit_transform(trn_x1)
print(cnt_wrd)

  (0, 73342)	4
  (0, 2662)	4
  (0, 66562)	11
  (0, 63783)	1
  (0, 27963)	3
  (0, 19854)	1
  (0, 4753)	2
  (0, 66339)	19
  (0, 43526)	1
  (0, 43300)	11
  (0, 70920)	2
  (0, 62903)	1
  (0, 38991)	1
  (0, 67125)	9
  (0, 31095)	3
  (0, 44529)	2
  (0, 72259)	1
  (0, 46634)	1
  (0, 19380)	1
  (0, 30670)	1
  (0, 3258)	10
  (0, 66432)	1
  (0, 72253)	2
  (0, 73394)	1
  (0, 43761)	2
  :	:
  (24999, 12040)	3
  (24999, 70505)	1
  (24999, 57728)	1
  (24999, 9237)	1
  (24999, 67281)	1
  (24999, 15841)	1
  (24999, 41828)	1
  (24999, 36574)	1
  (24999, 2155)	1
  (24999, 28637)	1
  (24999, 65531)	1
  (24999, 3430)	1
  (24999, 69585)	1
  (24999, 12161)	1
  (24999, 24013)	1
  (24999, 9234)	1
  (24999, 17690)	1
  (24999, 15790)	1
  (24999, 17237)	1
  (24999, 37566)	1
  (24999, 61619)	1
  (24999, 69467)	1
  (24999, 34277)	1
  (24999, 12117)	2
  (24999, 69561)	1


In [15]:
# 5.2.03
# return dimensions of training set

cnt_wrd.shape

(25000, 74849)

In [16]:
# 5.2.03
# transform training set to array

print(cnt_wrd.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
# 5.2.03
# apply and fit tf_idf vectorization to training set

tf_idf = TfidfVectorizer()
trn_x1_tf = tf_idf.fit_transform(trn_x1)
trn_x1_tf = tf_idf.transform(trn_x1)

In [18]:
# 5.2.03
# return tf_idf vectorization of training set

print("n_samples: %d, n_features: %d" % trn_x1_tf.shape)

n_samples: 25000, n_features: 74849


In [19]:
# 5.2.03
# apply tf_idf vectorization to test set

tst_x1_tf = tf_idf.transform(tst_x1)

In [20]:
# 5.2.03
# return tf_idf vectorization of test set

print("n_samples: %d, n_features: %d" % tst_x1_tf.shape)

n_samples: 25000, n_features: 74849


In [21]:
# 5.2.05
# train logisitc regression

stpwrd = nltk.corpus.stopwords.words('english')
lemmatizer = WordNetLemmatizer()

In [22]:
# 5.2.05
# train logistic regression

for i in range(0, len(trn_x1)):
    rvw = re.sub('[^a-zA-Z]', ' ', trn_x1[i])
    rvw = rvw.lower()
    rvw = rvw.split()
    rvw = [lemmatizer.lemmatize(word) for word in rvw if not word in set(stpwrd)]
    rvw = ' '.join(rvw)
    trn_x2.append(rvw)

for i in range(0, len(tst_x1)):
    rvw = re.sub('[^a-zA-Z]', ' ', tst_x1[i])
    rvw = rvw.lower()
    rvw = rvw.split()
    rvw = [lemmatizer.lemmatize(word) for word in rvw if not word in set(stpwrd)]
    rvw = ' '.join(rvw)
    tst_x2.append(rvw)

In [23]:
# 5.2.05
# return trained logistic regression

trn_x2[10]

'happens army wetback towelheads godless eastern european commie gather force south border gary busey kick butt course another laughable example reagan era cultural fallout bulletproof waste decent supporting cast headed l q jones thalmus rasulala'

In [1]:
# 5.2.05
# apply classifier
# freezes on this step
# unable to proceed

nv_bys_class = MultinomialNB()
nv_bys_class.fit(trn_x1_tf, trn_y1)
pred_y = nv_bys_class.predict(tst_x1_tf)

NameError: name 'MultinomialNB' is not defined

In [21]:
# 5.2.06
# return accuracy
# unable to proceed

print(metrics.classification_report(tst_y2, pred_y, target_names=['positive', 'negative']))

NameError: name 'tst_y2' is not defined

In [22]:
# 5.2.07
# return confusion matrix
# unable to proceed

print("confusion matrix:")
print(metrics.confusion_matrix(tst_y2, pred_y))

confusion matrix:


NameError: name 'tst_y2' is not defined

In [23]:
# 5.2.05
# train logisitc regression
# unable to proceed

logr = linear_model.LogisticRegression()
logr.fit(trn_x1_tf,trn_x2)

ValueError: Found input variables with inconsistent numbers of samples: [25000, 0]

In [24]:
# 5.2.05
# return predicted
# unable to proceed

predicted = logr.predict(numpy.array([3.46]).reshape(-1,1))

NameError: name 'numpy' is not defined

In [25]:
# 5.2.08
# func f1 score
# unable to proceed

def f1_sc(pc, rc):
    return 2*((pc*rc)/(pc+rc))

In [26]:
# 5.2.08
# get precision
# unable to proceed

precision = []

for i in np.arrange(pred_y):
    precision.append(i)
precision.append(pred_y)

AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
# 5.2.08
# get recall
# unable to proceed

recall = []

for i in np.arrange(pred_y):
    recall.append(i)
recall.append(pred_y)

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
# 5.2.08
# get f1 score
# unable to proceed

f1_score = []

for pr in zip (precision, recall):
    f1_score.append(f1_sc(pc, rc))

In [29]:
# 5.2.09
# define metrics
# unable to proceed

pred_y_prob = log_regression.predict_proba(tst_x1_tf)[::,1]
fpr, tpr, _ = metrics.roc_curve(tst_y1, pred_y_prob)

NameError: name 'log_regression' is not defined

In [30]:
# 5.2.09
# create a ROC curve
# unable to proceed

plt.plot(fpr,tpr)
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

NameError: name 'fpr' is not defined

In [31]:
# 5.2.10
# KNN classifier

# assign values to x and y variables:
x3 = dt01.iloc[:, :-1].values
y3 = dt01.iloc[:, 1].values

# split into random train and test subsets:
trn_x3, tst_x3, trn_y3, tst_y3 = train_test_split(x3, y3, test_size=0.50) 

# standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(trn_x3)
trn_x3 = scaler.transform(trn_x3)
tst_x3 = scaler.transform(tst_x3) 

# sse KNN classifier to fit data:
clssfr = KNeighborsClassifier(n_neighbors=5)
clssfr.fit(trn_x3, trn_y3)

# predict y data with classifier:
pred_y3 = clssfr.predict(trn_x3)

# return results:
print(confusion_matrix(tst_y3, pred_y3))
print(classification_report(tst_y3, pred_y3))

[[3161 3064]
 [3114 3161]]
              precision    recall  f1-score   support

           0       0.50      0.51      0.51      6225
           1       0.51      0.50      0.51      6275

    accuracy                           0.51     12500
   macro avg       0.51      0.51      0.51     12500
weighted avg       0.51      0.51      0.51     12500

